# Generated by Django 5.1.6 on 2025-03-07 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("container_id", models.CharField(max_length=255)),
                ("container_pdfname", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_user",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("railway_date", models.DateField(blank=True, null=True)),
                ("pickup_date", models.DateField(blank=True, null=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("empty_date", models.DateField(blank=True, null=True)),
                (
                    "pickup_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("invoice_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "invoice_pdfname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserAndPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permissionIndex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="container.permission",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("username", "permissionIndex")},
            },
        ),
    ]
