# Generated by Django 5.1.6 on 2025-06-17 03:35

import container.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from ..constants import constants_address

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlineOrderRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_number", models.CharField(max_length=255)),
                ("order_number", models.CharField(max_length=255)),
                ("po_number", models.CharField(max_length=255)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("pdf_name", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("ispay", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Carrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "address",
                    models.CharField(
                        default=constants_address.rimei_address, max_length=255
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("belongTo", models.CharField(default="CabinetsDepot", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LogisticsCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("index", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RailwayStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
                ("address", models.CharField(default="", max_length=255)),
                ("telephone", models.CharField(default="", max_length=255)),
                ("fax", models.CharField(default="", max_length=255)),
                ("email", models.CharField(default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="RMCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClockRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        verbose_name="Weekday",
                    ),
                ),
                (
                    "morning_in",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Morning Clock In"
                    ),
                ),
                (
                    "morning_out",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Morning Clock Out"
                    ),
                ),
                (
                    "afternoon_in",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Afternoon Clock In"
                    ),
                ),
                (
                    "afternoon_out",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Afternoon Clock Out"
                    ),
                ),
                (
                    "evening_in",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Evening Clock In"
                    ),
                ),
                (
                    "evening_out",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Evening Clock Out"
                    ),
                ),
                (
                    "total_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Total Hours",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="container.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clock Record",
                "verbose_name_plural": "Clock Records",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="InboundCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Type", models.CharField(default="", max_length=255)),
                ("Name", models.CharField(default="", max_length=255)),
                ("Manufacturer", models.CharField(default="", max_length=255)),
                (
                    "Carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="container.carrier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Container",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("container_id", models.CharField(max_length=255)),
                ("container_pdfname", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_user",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("plts", models.IntegerField()),
                ("railway_date", models.DateField(blank=True, null=True)),
                ("pickup_date", models.DateField(blank=True, null=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("empty_date", models.DateField(blank=True, null=True)),
                (
                    "pickup_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_updateInventory", models.BooleanField(default=False)),
                (
                    "lot",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("refnumber", models.CharField(blank=True, default="", max_length=255)),
                ("mbl", models.CharField(blank=True, default="", max_length=255)),
                ("weight", models.CharField(blank=True, default="", max_length=255)),
                ("invoice_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "invoice_pdfname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("ispay", models.BooleanField(default=False)),
                (
                    "customer_invoiceId",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customer_invoice_pdfname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customer_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("customer_invoice_date", models.DateField(blank=True, null=True)),
                ("customer_due_date", models.DateField(blank=True, null=True)),
                ("customer_payment_date", models.DateField(blank=True, null=True)),
                ("customer_ispay", models.BooleanField(default=False)),
                (
                    "Carrier",
                    models.ForeignKey(
                        default=container.models.get_default_carrier,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="container.carrier",
                    ),
                ),
                (
                    "inboundCategory",
                    models.ForeignKey(
                        default=container.models.get_default_inbound_category,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="container.inboundcategory",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        default=container.models.get_default_customer,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="container.invoicecustomer",
                    ),
                ),
                (
                    "logistics",
                    models.ForeignKey(
                        default=container.models.get_default_logistics,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="container.logisticscompany",
                    ),
                ),
                (
                    "railwayStation",
                    models.ForeignKey(
                        default=container.models.get_default_railstation_category,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="container.railwaystation",
                    ),
                ),
            ],
            options={
                "ordering": ["delivery_date"],
            },
        ),
        migrations.CreateModel(
            name="RMOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_num", models.CharField(max_length=255, unique=True)),
                ("po_num", models.CharField(max_length=255)),
                ("plts", models.IntegerField()),
                (
                    "order_pdfname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bol_pdfname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bill_to", models.CharField(blank=True, max_length=255, null=True)),
                ("ship_to", models.CharField(blank=True, max_length=255, null=True)),
                ("order_date", models.DateField(blank=True, null=True)),
                ("pickup_date", models.DateField(blank=True, null=True)),
                ("outbound_date", models.DateField(blank=True, null=True)),
                ("is_sendemail", models.BooleanField(default=False)),
                ("is_allocated_to_stock", models.BooleanField(default=False)),
                ("is_updateInventory", models.BooleanField(default=False)),
                ("is_canceled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_user",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customer_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="container.rmcustomer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="order_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="container.rmorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RMProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("shortname", models.CharField(blank=True, max_length=255, null=True)),
                ("size", models.CharField(blank=True, max_length=255, null=True)),
                ("TI", models.IntegerField(default=0)),
                ("HI", models.IntegerField(default=0)),
                ("Pallet", models.IntegerField(default=0)),
                ("Color", models.CharField(default="Other", max_length=255)),
                (
                    "Location",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "ShelfRecord",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "blongTo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="container.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RMInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_init", models.IntegerField(blank=True, null=True)),
                ("quantity_diff", models.IntegerField(default=0)),
                ("quantity", models.IntegerField()),
                ("quantity_for_neworder", models.IntegerField(default=0)),
                ("quantity_to_stock", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="container.rmproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="container.rmorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="container.rmproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContainerItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="container.container",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="container.rmproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContainerStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statement_number", models.CharField(max_length=100, unique=True)),
                ("statement_date", models.DateField(auto_now_add=True)),
                (
                    "paid_status",
                    models.CharField(
                        choices=[("unpaid", "Unpaid"), ("paid", "Paid")],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="container.container",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["statement_number"],
                        name="container_c_stateme_d87253_idx",
                    ),
                    models.Index(
                        fields=["container"], name="container_c_contain_58765d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserAndPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permissionIndex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="container.permission",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("username", "permissionIndex")},
            },
        ),
    ]
