# Generated by Django 5.1.6 on 2025-03-07 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RMCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RMOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_num", models.CharField(max_length=255)),
                ("po_num", models.CharField(max_length=255)),
                ("plts", models.IntegerField()),
                (
                    "bol_pdfname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pickup_date", models.DateField(blank=True, null=True)),
                ("outbound_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_user",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customer_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="container.rmcustomer",
                    ),
                ),
            ],
        ),
    ]
