# Generated by Django 4.1.7 on 2025-03-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='file_name',
            new_name='container_pdfname',
        ),
        migrations.AddField(
            model_name='container',
            name='container_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='created_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='empty_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='invoice_pdfname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='pickup_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='railway_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
