# Generated by Django 5.1.6 on 2025-03-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0002_rename_file_name_container_container_pdfname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="container_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="container",
            name="container_pdfname",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
