# Generated by Django 5.1.6 on 2025-03-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0002_rmcustomer_rmorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="rmorder",
            name="is_sendemail",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rmorder",
            name="is_updateInventory",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="rmorder",
            name="so_num",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
