# Generated by Django 5.1.6 on 2025-06-18 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0002_containerstatement_container_id_str"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="containerstatement",
            name="paid_status",
        ),
    ]
