# Generated by Django 4.1.7 on 2025-03-06 04:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('container', '0003_permission_userandpermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userandpermission',
            old_name='userId',
            new_name='username',
        ),
        migrations.AlterUniqueTogether(
            name='userandpermission',
            unique_together={('username', 'permissionIndex')},
        ),
    ]
