# Generated by Django 5.1.6 on 2025-06-18 03:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0003_remove_containerstatement_paid_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="containerstatement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="containerstatement",
            name="created_user",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
