# Generated by Django 5.1.6 on 2025-06-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0004_containerstatement_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rmproduct",
            name="quantity_diff",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rmproduct",
            name="quantity_init",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
