# Generated by Django 5.1.6 on 2025-03-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0004_orderimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="plts",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
