# Generated by Django 5.1.6 on 2025-06-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0005_rmproduct_quantity_diff_rmproduct_quantity_init"),
    ]

    operations = [
        migrations.AddField(
            model_name="rmproduct",
            name="type",
            field=models.CharField(default="Rimei", max_length=255),
        ),
    ]
