# Generated by Django 5.1.6 on 2025-06-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0006_rmproduct_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
            ],
        ),
    ]
