# Generated by Django 5.1.6 on 2025-06-24 03:21

import container.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0007_manufacturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="manufacturer",
            field=models.ForeignKey(
                default=container.models.get_default_manufacturer,
                on_delete=django.db.models.deletion.CASCADE,
                to="container.manufacturer",
            ),
        ),
    ]
