# Generated by Django 5.1.6 on 2025-03-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0007_rmorder_bill_to_rmorder_order_date_rmorder_ship_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClockRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        verbose_name="Week",
                    ),
                ),
                (
                    "morning_in",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Morning start time"
                    ),
                ),
                (
                    "morning_out",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Morning leave time"
                    ),
                ),
                (
                    "afternoon_in",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Afternoon start time"
                    ),
                ),
                (
                    "afternoon_out",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Afternoon leave time"
                    ),
                ),
                (
                    "evening_in",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Evening start time"
                    ),
                ),
                (
                    "evening_out",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Evening leave time"
                    ),
                ),
                (
                    "total_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Total working hours (hours)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Clocking record",
                "verbose_name_plural": "Clocking record",
                "ordering": ["-date"],
            },
        ),
    ]
