# Generated by Django 5.1.6 on 2025-06-24 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0008_container_manufacturer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inboundcategory",
            name="Carrier",
        ),
        migrations.RemoveField(
            model_name="inboundcategory",
            name="Manufacturer",
        ),
    ]
