# Generated by Django 5.1.6 on 2025-07-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0009_remove_inboundcategory_carrier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="containeritem",
            name="pallet",
            field=models.IntegerField(default=0),
        ),
    ]
