# Generated by Django 5.1.6 on 2025-03-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0009_employee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clockrecord",
            options={
                "ordering": ["-date"],
                "verbose_name": "Clock Record",
                "verbose_name_plural": "Clock Records",
            },
        ),
        migrations.AlterField(
            model_name="clockrecord",
            name="afternoon_in",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Afternoon Clock In"
            ),
        ),
        migrations.AlterField(
            model_name="clockrecord",
            name="afternoon_out",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Afternoon Clock Out"
            ),
        ),
        migrations.AlterField(
            model_name="clockrecord",
            name="evening_in",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Evening Clock In"
            ),
        ),
        migrations.AlterField(
            model_name="clockrecord",
            name="evening_out",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Evening Clock Out"
            ),
        ),
        migrations.AlterField(
            model_name="clockrecord",
            name="morning_in",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Morning Clock In"
            ),
        ),
        migrations.AlterField(
            model_name="clockrecord",
            name="morning_out",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Morning Clock Out"
            ),
        ),
        migrations.AlterField(
            model_name="clockrecord",
            name="total_hours",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="Total Hours"
            ),
        ),
        migrations.AlterField(
            model_name="clockrecord",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                verbose_name="Weekday",
            ),
        ),
    ]
