# Generated by Django 5.2.6 on 2025-09-13 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0011_invoicepaidcustomer_invoicepurposefor_invoicevendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceAPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=255)),
                ('invoice_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateField()),
                ('givetoboss_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('ar_invoice_pdfname', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.carrier')),
                ('purposefor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.invoicepurposefor')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.invoicevendor')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceARRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=255)),
                ('invoice_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateField()),
                ('givetoboss_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('ar_invoice_pdfname', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.carrier')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.invoicepaidcustomer')),
            ],
        ),
    ]
