# Generated by Django 5.1.6 on 2025-03-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0012_clockrecord_employee_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="rmproduct",
            name="shortname",
            field=models.TextField(max_length=255, null=True),
        ),
    ]
