# Generated by Django 5.2.6 on 2025-09-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0012_invoiceaprecord_invoicearrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='shortname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
