# Generated by Django 5.2.6 on 2025-09-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0013_carrier_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicearrecord',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
