# Generated by Django 5.1.6 on 2025-03-18 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0014_orderitem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClockRecord",
        ),
    ]
