# Generated by Django 5.2.6 on 2025-09-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0014_invoicearrecord_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceaprecord',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicearrecord',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
