# Generated by Django 5.2.6 on 2025-09-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0015_alter_invoiceaprecord_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceaprecord',
            name='ar_invoice_pdfname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoicearrecord',
            name='ar_invoice_pdfname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
