# Generated by Django 5.2.8 on 2025-12-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0016_alter_invoiceaprecord_ar_invoice_pdfname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='RMInventory',
        ),
    ]
