# Generated by Django 5.1.6 on 2025-03-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0016_clockrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clockrecord",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
