# Generated by Django 5.2.8 on 2025-12-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0017_rmproduct_price_delete_rminventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmproduct',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
