# Generated by Django 5.1.6 on 2025-03-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0018_alter_clockrecord_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="belongTo",
            field=models.CharField(default="GoldenFeather", max_length=255),
        ),
    ]
