# Generated by Django 5.2.10 on 2026-01-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0019_officesupplyitem_officesupplyplatform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officesupplyitem',
            name='price',
        ),
        migrations.AddField(
            model_name='officesupplyrecord',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
