# Generated by Django 5.2.10 on 2026-01-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0020_remove_officesupplyitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmorder',
            name='invoice_pdfname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
