# Generated by Django 5.1.6 on 2025-03-20 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0020_rmorder_order_pdfname_alter_employee_belongto"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="container_items",
                        to="container.container",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="container.rmproduct",
                    ),
                ),
            ],
        ),
    ]
