# Generated by Django 5.2.10 on 2026-01-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0021_rmorder_invoice_pdfname'),
    ]

    operations = [
        migrations.AddField(
            model_name='officesupplyrecord',
            name='storage_pdf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
