# Generated by Django 5.1.6 on 2025-03-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0021_containeritem"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlineOrderRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_number", models.CharField(max_length=255)),
                ("order_number", models.CharField(max_length=255)),
                ("po_number", models.CharField(max_length=255)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("pdf_name", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
    ]
