# Generated by Django 5.2.11 on 2026-02-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0022_officesupplyrecord_storage_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='clearance_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='clearance_ispay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='container',
            name='clearance_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='clearance_pdfname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='clearance_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rmorder',
            name='customer_ispay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rmorder',
            name='customer_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rmorder',
            name='customer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
