# Generated by Django 5.1.6 on 2025-04-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0022_alineorderrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="rmorder",
            name="is_canceled",
            field=models.BooleanField(default=False),
        ),
    ]
