# Generated by Django 5.2.12 on 2026-03-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0023_container_clearance_id_container_clearance_ispay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmorder',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
