# Generated by Django 5.1.6 on 2025-04-14 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0023_rmorder_is_canceled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="container",
            options={"ordering": ["delivery_date"]},
        ),
        migrations.AddField(
            model_name="container",
            name="customer",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="container.invoicecustomer",
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="logistics",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="container.logisticscompany",
            ),
        ),
    ]
