# Generated by Django 5.1.6 on 2025-04-18 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0024_alter_container_options_container_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rminventory",
            name="quantity_for_neworder",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rminventory",
            name="quantity_to_stock",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rmorder",
            name="is_allocated_to_stock",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="containeritem",
            name="container",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="container.container"
            ),
        ),
    ]
