# Generated by Django 5.2.12 on 2026-03-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0024_rmorder_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmcustomer',
            name='classification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
