# Generated by Django 5.2.12 on 2026-04-15 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0025_rmcustomer_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pallet_usage', models.DecimalField(decimal_places=2, help_text='该类型产品占用托盘', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='CabinetSalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True)),
                ('po_no', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CabinetProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('sku_short', models.CharField(max_length=50)),
                ('product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='container.cabinetproducttype')),
            ],
        ),
        migrations.CreateModel(
            name='CabinetSalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='container.cabinetsalesorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='container.cabinetproduct')),
            ],
        ),
    ]
