# Generated by Django 5.1.6 on 2025-04-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0025_rminventory_quantity_for_neworder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rmproduct",
            name="size",
            field=models.TextField(max_length=255, null=True),
        ),
    ]
