# Generated by Django 5.2.13 on 2026-04-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0026_cabinetproducttype_cabinetsalesorder_cabinetproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetsalesorder',
            name='order_pdfname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
