# Generated by Django 5.1.6 on 2025-04-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0026_rmproduct_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rmproduct",
            name="shortname",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rmproduct",
            name="size",
            field=models.TextField(blank=True, null=True),
        ),
    ]
