# Generated by Django 5.2.13 on 2026-04-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0027_cabinetsalesorder_order_pdfname'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmorder',
            name='so_num_actual',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
