# Generated by Django 5.1.6 on 2025-04-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0028_alter_rmproduct_shortname_alter_rmproduct_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="rminventory",
            name="quantity_init",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
