# Generated by Django 5.2.13 on 2026-04-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0028_rmorder_so_num_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rmorder',
            name='so_num_actual',
        ),
    ]
