# Generated by Django 5.1.6 on 2025-04-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0029_rminventory_quantity_init"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="is_updateInventory",
            field=models.BooleanField(default=False),
        ),
    ]
