# Generated by Django 5.2.13 on 2026-04-28 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0029_remove_rmorder_so_num_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='container.rmproduct'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='container.rmproduct'),
        ),
    ]
