# Generated by Django 5.2.13 on 2026-04-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0030_orderitem_product_actual_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_actual',
        ),
    ]
