# Generated by Django 5.1.6 on 2025-04-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0030_container_is_updateinventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="rmproduct",
            name="HI",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rmproduct",
            name="Pallet",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rmproduct",
            name="TI",
            field=models.IntegerField(default=0),
        ),
    ]
