# Generated by Django 5.1.6 on 2025-04-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0031_rmproduct_hi_rmproduct_pallet_rmproduct_ti"),
    ]

    operations = [
        migrations.AddField(
            model_name="rmproduct",
            name="Color",
            field=models.CharField(default="Red", max_length=255),
        ),
    ]
