# Generated by Django 5.2.13 on 2026-04-28 18:34

from django.db import migrations
from django.db.models import F

def copy_product(apps, schema_editor):
    Model = apps.get_model('container', 'OrderItem')

    # 把 product 复制到 product_actual
    Model.objects.filter(product_actual__isnull=True).update(
        product_actual=F('product')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0032_orderitem_product_actual'),
    ]

    operations = [
        migrations.RunPython(copy_product),
    ]
