# Generated by Django 5.1.6 on 2025-04-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0032_rmproduct_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="rminventory",
            name="quantity_diff",
            field=models.IntegerField(default=0),
        ),
    ]
