# Generated by Django 5.2.13 on 2026-05-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0033_copy_product_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmorder',
            name='carrier_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
