# Generated by Django 5.1.6 on 2025-05-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0033_rminventory_quantity_diff"),
    ]

    operations = [
        migrations.AddField(
            model_name="rmproduct",
            name="Location",
            field=models.CharField(default="", max_length=255),
        ),
    ]
