# Generated by Django 5.1.6 on 2025-05-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0034_rmproduct_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="rmproduct",
            name="ShelfRecord",
            field=models.CharField(default="", max_length=255),
        ),
    ]
