# Generated by Django 5.2.13 on 2026-05-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0034_rmorder_carrier_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmorder',
            name='carrier_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
