# Generated by Django 5.2.14 on 2026-06-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0035_rmorder_carrier_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmproduct',
            name='status',
            field=models.CharField(default='Common', max_length=255),
        ),
    ]
