# Generated by Django 5.1.6 on 2025-05-02 03:48

import container.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0037_carrier_inboundcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="inboundCategory",
            field=models.ForeignKey(
                default=container.models.get_default_inbound_category,
                on_delete=django.db.models.deletion.CASCADE,
                to="container.inboundcategory",
            ),
        ),
    ]
