# Generated by Django 5.1.6 on 2025-05-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0038_container_inboundcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="lot",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
