# Generated by Django 5.1.6 on 2025-05-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0039_container_lot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rmproduct",
            name="Location",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="rmproduct",
            name="ShelfRecord",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
