# Generated by Django 5.1.6 on 2025-05-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0041_inboundcategory_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RailwayStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
                ("address", models.CharField(default="", max_length=255)),
                ("telephone", models.CharField(default="", max_length=255)),
                ("fax", models.CharField(default="", max_length=255)),
                ("email", models.CharField(default="", max_length=255)),
            ],
        ),
    ]
