# Generated by Django 5.1.6 on 2025-05-06 04:23

import container.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0042_railwaystation"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="railwayStation",
            field=models.ForeignKey(
                default=container.models.get_default_railstation_category,
                on_delete=django.db.models.deletion.CASCADE,
                to="container.railwaystation",
            ),
        ),
    ]
