# Generated by Django 5.1.6 on 2025-05-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0043_container_railwaystation"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="mbl",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="container",
            name="refnumber",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
