# Generated by Django 5.1.6 on 2025-05-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0044_container_mbl_container_refnumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrier",
            name="address",
            field=models.CharField(
                default="1285 101st St\nLemont IL 60439", max_length=255
            ),
        ),
    ]
