# Generated by Django 5.1.6 on 2025-05-07 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0045_carrier_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="Carrier",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="container.carrier",
            ),
        ),
    ]
