# Generated by Django 5.1.6 on 2025-05-07 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0046_container_carrier"),
    ]

    operations = [
        migrations.AddField(
            model_name="alineorderrecord",
            name="ispay",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="container",
            name="Carrier",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="container.carrier",
            ),
        ),
    ]
