# Generated by Django 5.1.6 on 2025-05-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0047_alineorderrecord_ispay_alter_container_carrier"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="ispay",
            field=models.BooleanField(default=False),
        ),
    ]
