# Generated by Django 5.1.6 on 2025-05-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0048_container_ispay"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
