# Generated by Django 5.1.6 on 2025-05-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0049_container_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="container",
            name="invoice_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
