# Generated by Django 5.1.6 on 2025-05-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0050_container_due_date_container_invoice_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="customer_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="container",
            name="customer_invoiceId",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="container",
            name="customer_invoice_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="container",
            name="customer_invoice_pdfname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="container",
            name="customer_ispay",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="container",
            name="customer_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="container",
            name="customer_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="container",
            name="payment_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
