# Generated by Django 5.1.6 on 2025-05-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0051_container_customer_due_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alineorderrecord",
            name="payment_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
