# Generated by Django 5.1.6 on 2025-05-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0052_alineorderrecord_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="weight",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
