# Generated by Django 5.1.6 on 2025-05-14 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0053_container_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="rmproduct",
            name="blongTo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="container.employee",
            ),
        ),
    ]
