# Generated by Django 5.1.6 on 2025-03-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0010_alter_clockrecord_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogisticsCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
