# Generated by Django 5.1.6 on 2025-03-18 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0015_delete_clockrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClockRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        verbose_name="Weekday",
                    ),
                ),
                (
                    "morning_in",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Morning Clock In"
                    ),
                ),
                (
                    "morning_out",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Morning Clock Out"
                    ),
                ),
                (
                    "afternoon_in",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Afternoon Clock In"
                    ),
                ),
                (
                    "afternoon_out",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Afternoon Clock Out"
                    ),
                ),
                (
                    "evening_in",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Evening Clock In"
                    ),
                ),
                (
                    "evening_out",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Evening Clock Out"
                    ),
                ),
                (
                    "total_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Total Hours",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="container.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clock Record",
                "verbose_name_plural": "Clock Records",
                "ordering": ["-date"],
            },
        ),
    ]
