# Generated by Django 5.1.6 on 2025-03-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0017_alter_clockrecord_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clockrecord",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
